config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get 'restaurants', to: 'restaurants#index'
  # get 'restaurants/new', to: 'restaurants#new'
  # post 'restaurants', to: 'restaurants#create'

  # get 'restaurants/:id', to: 'restaurants#show', as: 'show_restaurants'
  Rails.application.routes.draw do
    resources :restaurants do
      resources :reviews, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurants_params)
    @restaurant.save
    redirect_to show_restaurants_path(@restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
    @review = Review.new
  end

  private

  def restaurants_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>My Restaurant's List</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurants_path(restaurant) %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

<%= link_to 'View Restaurant', restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Restaurant Details</h1>
<p><%= @restaurant.name %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>

<% if @restaurant.reviews.any? %>
  <h4>Reviews:</h4>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li><%= review.content %> - <%= review.rating %> stars</li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews yet.</p>
<% end %>

<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back to Restaurant List', restaurants_path %>